In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib_inline.backend_inline

# 그래프의 폰트 출력을 선명하게 (svg, retina 등이 있음)
matplotlib_inline.backend_inline.set_matplotlib_formats("png2x")
# 테마 설정: "default", "classic", "dark_background", "fivethirtyeight", "seaborn"
mpl.style.use("default")
# 이미지가 레이아웃 안으로 들어오도록 함
# https://matplotlib.org/stable/users/explain/axes/constrainedlayout_guide.html
mpl.rcParams.update({"figure.constrained_layout.use": True})

#font, line, marker 등의 배율 설정: paper, notebook, talk, poster
sns.set_context("paper") 
#배색 설정: tab10, Set2, Accent, husl
sns.set_palette("Set2") 
#눈금, 배경, 격자 설정: ticks, white, whitegrid, dark, darkgrid
# withegrid: 눈금을 그리고, 각 축의 눈금을 제거
sns.set_style("whitegrid") 

In [3]:
# 로컬에서 

plt.rc("font", family = "D2Coding")
plt.rcParams["axes.unicode_minus"] = False

In [4]:
import os, natsort, re
from tqdm import tqdm
import time, random

In [5]:
PRJCT_PATH = '/home/doeun/code/AI/ESTSOFT2024/workspace/2.project_text/aladin_usedbook/'
save_dir = 'processed/'

In [6]:
bookinfo_name = 'encoded_bookinfo_ver{}.pkl'.format(0.75)
usedinfo_name = 'encoded_usedinfo_ver{}.csv'.format(0)
bookinfo_path = os.path.join(PRJCT_PATH,save_dir,bookinfo_name)
usedinfo_path = os.path.join(PRJCT_PATH,save_dir,usedinfo_name)

In [7]:
usedinfo = pd.read_csv(usedinfo_path)

import pickle

with open(bookinfo_path,'rb') as f:
    bookinfo = pickle.load(f)

display(usedinfo)
display(bookinfo )

ItemId  quality  store  price
0      1000152        2     26   7300
1      1000152        2     16   7400
2      1000152        2     25   7400
3      1000152        3     41   7700
4      1000152        3     16   7700
...        ...      ...    ...    ...
70234   999466        2     33   5000
70235   999466        2     13   5000
70236   999466        2     47   5000
70237   999466        2     11   5000
70238   999466        2     19   5000

[70239 rows x 4 columns]

BName  \
0     [8075, 353, 61, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
1     [219, 40, 2, 1847, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2     [925, 79, 124, 6, 1081, 0, 0, 0, 0, 0, 0, 0, 0...   
3     [3061, 726, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...   
4     [1081, 2, 214, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...   
...                                                 ...   
9323  [4284, 2, 3488, 3814, 198, 0, 0, 0, 0, 0, 0, 0...   
9324  [1806, 2, 1937, 327, 0, 0, 0, 0, 0, 0, 0, 0, 0...   
9325  [1147, 2270, 406, 399, 770, 5268, 115, 67, 80,...   
9326  [496, 2, 148, 3, 6700, 12, 0, 0, 0, 0, 0, 0, 0...   
9327  [1193, 102, 5880, 216, 356, 23, 1264, 0, 0, 0,...   

                                              BName_sub     ItemId  Author  \
0     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...      54947       0   
1     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...     168173    1727   
2     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...     458277       0   
3     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...     128759    1467   
4     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...     131488    3427   
...                                                 ...        ...     ...   
9323  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  342597187    1038   
9324  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  342597589    1579   
9325  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  342597714    1488   
9326  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  342388828     468   
9327  [8, 957, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...  342594262      96   

      Author_mul  Publshr      Pdate  RglPrice  SlsPrice  SalesPoint  \
0          False        0 1979-10-01      5500      4950       177.0   
1          False        0 1979-12-01      2800      2660      1960.0   
2          False        0 1980-12-01      4500      4050       552.0   
3          False       48 1983-06-01      6000      6000       409.0   
4          False        0 1984-07-01     12000     12000      1110.0   
...          ...      ...        ...       ...       ...         ...   
9323        True        2 2024-07-25      6000      5400     10530.0   
9324        True        2 2024-07-25      6000      5400      5870.0   
9325        True        2 2024-07-25      6000      5400      6370.0   
9326        True        0 2024-07-31     13000     11700      8190.0   
9327        True        9 2024-07-31     25000     22500     89930.0   

               Category  
0      [20, 0, 0, 0, 0]  
1     [43, 1, 44, 0, 0]  
2     [43, 1, 44, 0, 0]  
3     [32, 22, 0, 0, 0]  
4     [43, 1, 44, 0, 0]  
...                 ...  
9323    [7, 0, 0, 0, 0]  
9324    [7, 0, 0, 0, 0]  
9325    [7, 0, 0, 0, 0]  
9326  [133, 0, 0, 0, 0]  
9327   [18, 0, 0, 0, 0]  

[9328 rows x 11 columns]

In [8]:
display(usedinfo.info())
display(bookinfo.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70239 entries, 0 to 70238
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ItemId   70239 non-null  int64
 1   quality  70239 non-null  int64
 2   store    70239 non-null  int64
 3   price    70239 non-null  int64
dtypes: int64(4)
memory usage: 2.1 MB


None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9328 entries, 0 to 9327
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype         
---  ------      --------------  -----         
 0   BName       9328 non-null   object        
 1   BName_sub   9328 non-null   object        
 2   ItemId      9328 non-null   int64         
 3   Author      9328 non-null   int64         
 4   Author_mul  9328 non-null   bool          
 5   Publshr     9328 non-null   int64         
 6   Pdate       9328 non-null   datetime64[ns]
 7   RglPrice    9328 non-null   int64         
 8   SlsPrice    9328 non-null   int64         
 9   SalesPoint  9328 non-null   float64       
 10  Category    9328 non-null   object        
dtypes: bool(1), datetime64[ns](1), float64(1), int64(5), object(3)
memory usage: 738.0+ KB


None

In [66]:
from sklearn.model_selection import train_test_split

def lists_append_together(lists:list,data:list):
    tuple(map(lambda x : x[0].append(x[1]),zip(lists,data)))
    return lists

def train_test_split_strat(X:pd.DataFrame,y:pd.Series,strat=None,method='order',n_strata=10,**kwargs):
    type_x,type_y = type(X), type(y)
    assert type_x == type_y 
    if strat is None : strat = y
    if method in ['quantile','order'] :
        p_arr = np.linspace(0,n_strata)/n_strata
        cut_p = np.quantile(strat,p_arr)
    elif method == 'value':
        cut_p = np.linspace(np.min(strat)-1,np.max(strat),n_strata)
    cut_p[-1] = np.max(strat)+1
    train_Xs,test_Xs,train_ys,test_ys = [],[],[],[]
    data = [train_Xs,test_Xs,train_ys,test_ys]
    res_Xs,res_ys =[],[]
    for p_a,p_b in zip(cut_p[:-1],cut_p[1:]):
        cond= (p_a <= strat) & (strat < p_b)
        input_X, input_y = X[cond], y[cond]
        if len(input_X) == 0 : continue
        if len(input_X) == 1 : 
            res_Xs.append(input_X), res_ys.append(input_y)
        else :
            splited = train_test_split(input_X,input_y,**kwargs)
            data = lists_append_together(data,splited)
    if len(res_Xs) > 1 :
        input_X, input_y = pd.concat(res_Xs), pd.concat(res_ys)
        splited = train_test_split(input_X,input_y,**kwargs)
        data = lists_append_together(data,splited)
    elif len(res_Xs) == 1:
        data[0],data[2] = lists_append_together([data[0],data[2]],[res_Xs[0],res_ys[0]])
    
    if type_x == type(np.array([])) :
        func1 = lambda x : x.reshape(len(x),-1)
        func = lambda x : np.vstack(map(func1,x))
    else : func = pd.concat
    return tuple(map(func,data))

In [11]:
usedinfo.columns

Index(['ItemId', 'quality', 'store', 'price'], dtype='object')

### match bookinfo for each usedbook

In [21]:
bookinfo = bookinfo.set_index('ItemId')
bookinfo

BName  \
ItemId                                                         
54947      [8075, 353, 61, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
168173     [219, 40, 2, 1847, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
458277     [925, 79, 124, 6, 1081, 0, 0, 0, 0, 0, 0, 0, 0...   
128759     [3061, 726, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...   
131488     [1081, 2, 214, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...   
...                                                      ...   
342597187  [4284, 2, 3488, 3814, 198, 0, 0, 0, 0, 0, 0, 0...   
342597589  [1806, 2, 1937, 327, 0, 0, 0, 0, 0, 0, 0, 0, 0...   
342597714  [1147, 2270, 406, 399, 770, 5268, 115, 67, 80,...   
342388828  [496, 2, 148, 3, 6700, 12, 0, 0, 0, 0, 0, 0, 0...   
342594262  [1193, 102, 5880, 216, 356, 23, 1264, 0, 0, 0,...   

                                                   BName_sub  Author  \
ItemId                                                                 
54947      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...       0   
168173     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...    1727   
458277     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...       0   
128759     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...    1467   
131488     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...    3427   
...                                                      ...     ...   
342597187  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...    1038   
342597589  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...    1579   
342597714  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...    1488   
342388828  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...     468   
342594262  [8, 957, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...      96   

           Author_mul  Publshr      Pdate  RglPrice  SlsPrice  SalesPoint  \
ItemId                                                                      
54947           False        0 1979-10-01      5500      4950       177.0   
168173          False        0 1979-12-01      2800      2660      1960.0   
458277          False        0 1980-12-01      4500      4050       552.0   
128759          False       48 1983-06-01      6000      6000       409.0   
131488          False        0 1984-07-01     12000     12000      1110.0   
...               ...      ...        ...       ...       ...         ...   
342597187        True        2 2024-07-25      6000      5400     10530.0   
342597589        True        2 2024-07-25      6000      5400      5870.0   
342597714        True        2 2024-07-25      6000      5400      6370.0   
342388828        True        0 2024-07-31     13000     11700      8190.0   
342594262        True        9 2024-07-31     25000     22500     89930.0   

                    Category  
ItemId                        
54947       [20, 0, 0, 0, 0]  
168173     [43, 1, 44, 0, 0]  
458277     [43, 1, 44, 0, 0]  
128759     [32, 22, 0, 0, 0]  
131488     [43, 1, 44, 0, 0]  
...                      ...  
342597187    [7, 0, 0, 0, 0]  
342597589    [7, 0, 0, 0, 0]  
342597714    [7, 0, 0, 0, 0]  
342388828  [133, 0, 0, 0, 0]  
342594262   [18, 0, 0, 0, 0]  

[9328 rows x 10 columns]

In [22]:
bookinfo.columns

Index(['BName', 'BName_sub', 'Author', 'Author_mul', 'Publshr', 'Pdate',
       'RglPrice', 'SlsPrice', 'SalesPoint', 'Category'],
      dtype='object')

In [23]:
book_cols = ['BName', 'BName_sub', 'Author', 'Author_mul', 'Publshr', 'Pdate',
       'RglPrice', 'SlsPrice', 'SalesPoint', 'Category']
for col in book_cols:
    usedinfo[col] = usedinfo['ItemId'].apply(lambda x: bookinfo.loc[x,col])

usedinfo

ItemId  quality  store  price  \
0      1000152        2     26   7300   
1      1000152        2     16   7400   
2      1000152        2     25   7400   
3      1000152        3     41   7700   
4      1000152        3     16   7700   
...        ...      ...    ...    ...   
70234   999466        2     33   5000   
70235   999466        2     13   5000   
70236   999466        2     47   5000   
70237   999466        2     11   5000   
70238   999466        2     19   5000   

                                                   BName  \
0      [2230, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1      [2230, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2      [2230, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3      [2230, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4      [2230, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
...                                                  ...   
70234  [3980, 325, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...   
70235  [3980, 325, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...   
70236  [3980, 325, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...   
70237  [3980, 325, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...   
70238  [3980, 325, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...   

                                               BName_sub  Author  Author_mul  \
0      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...      13       False   
1      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...      13       False   
2      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...      13       False   
3      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...      13       False   
4      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...      13       False   
...                                                  ...     ...         ...   
70234  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...     338        True   
70235  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...     338        True   
70236  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...     338        True   
70237  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...     338        True   
70238  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...     338        True   

       Publshr      Pdate  RglPrice  SlsPrice  SalesPoint          Category  
0            7 2007-10-30     12000     10800     57521.0   [4, 1, 3, 1, 5]  
1            7 2007-10-30     12000     10800     57521.0   [4, 1, 3, 1, 5]  
2            7 2007-10-30     12000     10800     57521.0   [4, 1, 3, 1, 5]  
3            7 2007-10-30     12000     10800     57521.0   [4, 1, 3, 1, 5]  
4            7 2007-10-30     12000     10800     57521.0   [4, 1, 3, 1, 5]  
...        ...        ...       ...       ...         ...               ...  
70234        0 2007-10-20      9000      8100     19046.0  [51, 0, 0, 0, 0]  
70235        0 2007-10-20      9000      8100     19046.0  [51, 0, 0, 0, 0]  
70236        0 2007-10-20      9000      8100     19046.0  [51, 0, 0, 0, 0]  
70237        0 2007-10-20      9000      8100     19046.0  [51, 0, 0, 0, 0]  
70238        0 2007-10-20      9000      8100     19046.0  [51, 0, 0, 0, 0]  

[70239 rows x 14 columns]

In [24]:
usedinfo.columns

Index(['ItemId', 'quality', 'store', 'price', 'BName', 'BName_sub', 'Author',
       'Author_mul', 'Publshr', 'Pdate', 'RglPrice', 'SlsPrice', 'SalesPoint',
       'Category'],
      dtype='object')

In [106]:
temp = usedinfo['Pdate']
display(type(temp.iloc[0]))
temp = temp.to_numpy(dtype=np.int64)
temp = temp//(1e11)
display(np.min(temp),np.max(temp))

pandas._libs.tslibs.timestamps.Timestamp

3128544.0

17072640.0

In [107]:
usedinfo['Pdate'] = temp
usedinfo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70239 entries, 0 to 70238
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   ItemId      70239 non-null  int64  
 1   quality     70239 non-null  int64  
 2   store       70239 non-null  int64  
 3   price       70239 non-null  int64  
 4   BName       70239 non-null  object 
 5   BName_sub   70239 non-null  object 
 6   Author      70239 non-null  int64  
 7   Author_mul  70239 non-null  bool   
 8   Publshr     70239 non-null  int64  
 9   Pdate       70239 non-null  float64
 10  RglPrice    70239 non-null  int64  
 11  SlsPrice    70239 non-null  int64  
 12  SalesPoint  70239 non-null  float64
 13  Category    70239 non-null  object 
dtypes: bool(1), float64(2), int64(8), object(3)
memory usage: 7.0+ MB


### make whole np.array data

In [108]:
cols_arry = ['Category','BName','BName_sub']
temp = usedinfo[cols_arry].values
temp.shape

(70239, 3)

In [109]:
temp_concat =np.apply_along_axis(np.hstack,1,temp)
display(temp_concat.shape,type(temp_concat))
display(temp_concat)

(70239, 60)

numpy.ndarray

array([[ 4,  1,  3, ...,  0,  0,  0],
       [ 4,  1,  3, ...,  0,  0,  0],
       [ 4,  1,  3, ...,  0,  0,  0],
       ...,
       [51,  0,  0, ...,  0,  0,  0],
       [51,  0,  0, ...,  0,  0,  0],
       [51,  0,  0, ...,  0,  0,  0]])

In [110]:
temp_concat[0]

array([   4,    1,    3,    1,    5, 2230,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0])

- (0,5) : category
- (5,35) : BName
- (35,60) : BName_sub

In [111]:
x_cols = ['ItemId', 'quality', 'store', 'BName', 'BName_sub', 'Author',
       'Author_mul', 'Publshr', 'Pdate', 'RglPrice', 'SlsPrice', 'SalesPoint',
       'Category']
xcols_scalar = list(filter(lambda x : x not in cols_arry+['ItemId'],x_cols))
xcols_scalar

['quality',
 'store',
 'Author',
 'Author_mul',
 'Publshr',
 'Pdate',
 'RglPrice',
 'SlsPrice',
 'SalesPoint']

In [112]:
x_scalar = usedinfo[xcols_scalar].values
X = np.hstack((temp_concat,x_scalar))

In [113]:
x_id = usedinfo['ItemId'].values.reshape(-1,1)
x_id.shape

(70239, 1)

In [114]:
X = np.hstack((x_id,X))
X.shape

(70239, 70)

In [115]:
type(X) == type(np.array([]))

True

### train val test split and scaling

In [116]:
y = usedinfo['price'].values

X_dev,X_test,y_dev,y_test = train_test_split_strat(X,y,strat=X[:,0],test_size=0.2,random_state=329)
X_train,X_val,y_train,y_val = train_test_split_strat(X_dev,y_dev,strat=X_dev[:,0],test_size=0.2,random_state=329)

/tmp/ipykernel_2683/4258426944.py:38: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  func = lambda x : np.vstack(map(func1,x))


In [117]:
display(X_train.shape)
display(X_val.shape)
display(X_test.shape)
display(y_train.shape)
display(y_val.shape)
display(y_test.shape)

(44919, 70)

(11254, 70)

(14066, 70)

(44919, 1)

(11254, 1)

(14066, 1)

In [118]:
from sklearn.preprocessing import MinMaxScaler

scale_partition = [(1,61)]+[(61+i,62+i) for i in range(9)]
scale_partition

[(1, 61),
 (61, 62),
 (62, 63),
 (63, 64),
 (64, 65),
 (65, 66),
 (66, 67),
 (67, 68),
 (68, 69),
 (69, 70)]

In [80]:
import copy
scaler_list = [copy.deepcopy(MinMaxScaler()) for _ in scale_partition]
scalers = list(zip(scale_partition,scaler_list))
scalers

[((1, 61), MinMaxScaler()),
 ((61, 62), MinMaxScaler()),
 ((62, 63), MinMaxScaler()),
 ((63, 64), MinMaxScaler()),
 ((64, 65), MinMaxScaler()),
 ((65, 66), MinMaxScaler()),
 ((66, 67), MinMaxScaler()),
 ((67, 68), MinMaxScaler()),
 ((68, 69), MinMaxScaler()),
 ((69, 70), MinMaxScaler())]

In [119]:
intermid = []
for (cols,scaler) in scalers:
    sliced = X_train[:,cols[0]:cols[1]]
    sliced = sliced.astype(np.float64)
    sliced = scaler.fit_transform(sliced)
    intermid.append(sliced)

X_train_scaled = np.hstack(intermid)

In [122]:
np.max(X_train_scaled,axis=0),np.min(X_train_scaled,axis=0)

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.,
        0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.]))

In [124]:
np.where(np.max(X_train_scaled,axis=0)==0)

(array([30, 31, 32, 33, 34]),)

In [125]:
intermid = []
for (cols,scaler) in scalers:
    sliced = X_val[:,cols[0]:cols[1]]
    sliced = sliced.astype(np.float64)
    sliced = scaler.transform(sliced)
    intermid.append(sliced)

X_val_scaled = np.hstack(intermid)
display(X_val_scaled.shape)
display(np.max(X_val_scaled,axis=0),np.min(X_val_scaled,axis=0))

(11254, 69)

array([1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 0.99472388, 0.99929668, 0.99882491,
       0.99530682, 0.99789104, 0.997303  , 1.        , 1.        ,
       0.95695131, 1.        , 1.        , 1.        , 0.99940199,
       1.        , 0.31506849, 0.03456253, 1.        , 0.04519906,
       0.19699199, 1.        , 0.24159664, 1.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       1.        , 0.98799376, 0.99284374, 1.        , 1.29839723,
       1.        , 1.        , 0.80318139, 0.56242103, 1.        ,
       1.        , 1.        , 1.        , 0.6690994 , 1.        ,
       1.        , 1.        , 1.        , 1.        , 0.95826645,
       1.        , 1.        , 0.91544885, 1.        , 1.        ,
       1.        , 1.        , 0.99971727, 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        ])

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
      

In [126]:
intermid = []
for (cols,scaler) in scalers:
    sliced = X_test[:,cols[0]:cols[1]]
    sliced = sliced.astype(np.float64)
    sliced = scaler.transform(sliced)
    intermid.append(sliced)

X_test_scaled = np.hstack(intermid)
display(X_test_scaled.shape)

(14066, 69)

In [127]:
dir_path = os.path.join(PRJCT_PATH,save_dir,'model_input')
dir_path

'/home/doeun/code/AI/ESTSOFT2024/workspace/2.project_text/aladin_usedbook/processed/model_input'

In [128]:
import pickle

def save_pkl(save_dir,file_name,save_object):
    if not os.path.exists(save_dir): os.mkdir(save_dir)
    file_path = os.path.join(save_dir,file_name)
    with open(file_path,'wb') as f:
        pickle.dump(save_object,f)

In [130]:
data_type = 'sample'
ver=0.75
save_pkl(dir_path,'{}.v{}_X_train.pkl'.format(data_type,ver),X_train_scaled)
save_pkl(dir_path,'{}.v{}_X_val.pkl'.format(data_type,ver),X_val_scaled)
save_pkl(dir_path,'{}.v{}_X_test.pkl'.format(data_type,ver),X_test_scaled)
save_pkl(dir_path,'{}.v{}_y_train.pkl'.format(data_type,ver),y_train)
save_pkl(dir_path,'{}.v{}_y_val.pkl'.format(data_type,ver),y_val)
save_pkl(dir_path,'{}.v{}_y_test.pkl'.format(data_type,ver),y_test)